openapi: 3.0.0
info:
  title: Bankcard API
  version: '1.0'
  description: 银行卡API
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/collection/v1'
    description: Sandbox
  - url: 'https://global-api.lianlianpay.com/collection/v1'
    description: Production
paths:
  /bankcards:
    get:
      summary: 查询客户提现银行账号信息
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: string
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/BankAccountInfo'
      operationId: get-bankAccounts
      description: 该接口支持按币种查询客户提现银行账号信息。
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: 币种
        - schema:
            type: string
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: string
          in: query
          name: pageNum
          description: 页码
          required: true
      tags:
        - bankAccount
components:
  schemas:
    BankAccountInfo:
      title: BankAccountInfo
      type: object
      description: 提现银行账号对象
      x-tags:
        - bankAccount
      properties:
        id:
          type: string
          description: 账号ID
        bankAccountNo:
          type: string
          description: 提现银行账号
        bankAccountName:
          type: string
          description: 提现银行账号户名
        bankName:
          type: string
          description: 银行名称
        currency:
          type: string
          description: '币种列表 ["USD"]'
        district:
          type: string
          description: 地区
        bankAccountType:
          type: string
          description: |
            银行卡类型

            id|message
            -|-
            0|借记卡
            1|信用卡
            2|对公银行账号
      required:
        - id
        - bankAccountNo
        - bankAccountName
        - bankName
        - currency
        - district
        - bankAccountType
