openapi: 3.0.0
info:
  title: Bankcard API
  version: '1.0'
  description: 银行卡API
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/collection/v1'
    description: Sandbox
  - url: 'https://global-api.lianlianpay.com/collection/v1'
    description: Production
paths:
  /bankcards:
    get:
      summary: 查询客户提现银行账号信息
      tags:
        - bankcard
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: string
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/BankCardInfo'
      operationId: get-bankcards
      description: ''
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: 币种
        - schema:
            type: string
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: string
          in: query
          name: pageNum
          description: 页码
          required: true
components:
  schemas:
    BankCardInfo:
      title: BankAccountInfo
      type: object
      description: 银行账号对象
      x-tags:
        - bankcard
      properties:
        id:
          type: string
          description: 账号ID
        bankAccountNumber:
          type: string
          description: 银行账号
        bankAccountName:
          type: string
          description: 持卡人姓名
        bankName:
          type: string
          description: 银行名称
        currency:
          type: string
          description: '币种列表 ["USD"]'
        district:
          type: string
          description: 地区
        bankAccountType:
          type: string
          description: 银行卡类型 0-借记卡，1-信用卡，2-对公银行账号
      required:
        - id
        - bankAccountNumber
        - bankAccountName
        - bankName
        - currency
        - district
        - bankAccountType
