openapi: 3.0.0
info:
  title: Shop API
  version: '1.0'
  description: 店铺API
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/collection/v1'
    description: Sandbox
  - url: 'https://global-api.lianlianpay.com/collection /v1'
    description: Production
paths:
  /shops:
    get:
      summary: 获取店铺列表
      tags:
        - shop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: string
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShopInfo'
      operationId: get-shops
      description: 按创建时间排序
      requestBody: {}
      parameters:
        - schema:
            type: string
            enum:
              - Amazon
              - PAYPAL
              - Ebay
              - Wish
              - CDiscount
              - Rakuten
              - DeRakuten
              - Mercado
              - Yandex
          in: query
          name: platform
          description: 平台类型
        - schema:
            type: string
          in: query
          name: region
          description: 地区
        - schema:
            type: string
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: string
          in: query
          name: pageNum
          description: 页码
          required: true
components:
  schemas:
    ShopInfo:
      title: ShopInfo
      type: object
      x-tags:
        - shop
      description: ''
      properties:
        platformId:
          type: string
          description: 平台id
        platform:
          type: string
          description: 平台类型
        sellerId:
          type: string
          description: 卖家编号
        id:
          type: string
          description: 店铺id
        shopName:
          type: string
          description: 店铺名称
        status:
          type: string
          description: 状态
        region:
          type: string
          description: 地区
        accountInfo:
          type: object
          description: 账号信息
          required:
            - accountId
            - virtualAccount
            - currency
            - accountName
            - region
            - bankName
            - appendInfo
          properties:
            accountId:
              type: string
              description: 账号id
            virtualAccount:
              type: string
              description: 虚拟账号
            currency:
              type: string
              description: 币种
            accountName:
              type: string
              description: 户名
            region:
              type: string
              description: 银行地区
            bankName:
              type: string
              description: 银行名称
            appendInfo:
              type: string
              description: 银行账号附加信息
        createTime:
          type: string
          description: 创建时间
      required:
        - platformId
        - platform
        - sellerId
        - id
        - shopName
        - status
        - region
        - accountInfo
        - createTime
